<table align="center" cellpadding="10"><tr><td><img src="../images/fundamentos_01.jpg" width="450" /></td><td>The documentary we present does not fall within the classi-cal framework of this genre. It won't be just an expositive work: the imprint and personality of the narrator will be pres-ent. His commitment is to describe his experiences with images that produce an afterthought carried through by the immediacy of cinematography. The guidelines for our documentary are: to observe, to register and outline new mental circuits around old subjects, well-known in our current global world, characterized by the speed at which changes occur. Our investigation will deal with the following themes: nomadism as an optional lifestyle; the coexistence of schedules and timelessness; the notion of distances; the language; the precariousness of the current equilibrium. These are complex issues that must be approached in the particular context of the Gobi: a wide-spread desert, filled with emptiness, where the minimal resources required for an audiovisual production seem out of reach.
</td></tr></table>
<table align="center" cellpadding="10"><tr><td>
In harmony with the nomad, who is forced to reduce his needs and material satisfactions to a minimum, to carry to an extreme the human possibilities of enduring the scourge of cold and hot weather, thirst, hunger and fatigue, we are faced with the production of a documentary with the endur-ance that these conditions shall demand. The story told is intimately bound to the possibilities (and lack of these) of its recounting, the production design and the filming are inevi-tably in a perpetual dialogue. In order to articulate this audiovisual project – based on the documents available regarding the Mongol culture- we shall avail ourselves of video and photographic recordings, music, fables and local stories, usages and details of the daily life of the nomadic families, historical data, poetry, fragments and anecdotes from the chronicles of travelers, geographic, geologic, cartographic and archeological material. <div align="right"><p>
                                        <a class="Button" href="modalidad.php">
                                          <span class="btn">
                                            <span class="t">More...</span>
                                            <span class="r"><span></span></span>
                                            <span class="l"></span>
                                          </span>
                                        </a>
                                  </p></div> </td><td><img src="../images/fundamentos_02.jpg" width="450" /></td></tr></table>