<table align="center" cellpadding="5">
<tr>
<td>
El tiempo sigue brumoso (cuesta creer que sea sólo smog), húmedo, con chaparrones que no dejan que el piso complete de secar nunca. Me levanté muy temprano para ser el primero en la cola del Consulado, lo que me permitió ver algo que pocos ven, la ciudad vacía. Vacías las calles, la estación de subterráneo, los vagones y los asientos. Nadie. Fue una sensación increíble. Como por raro pase mágico la marejada humana había desaparecido.<br />
La diferencia que siento entre los chinos y los persas es que los primeros con toda su fiebre de crecimiento es como si renegaran de su parte más oriental, hay una renuncia a su identidad en una búsqueda frenética por ser parte de un Primer Mundo que ya están conformando y reformando. Pero el encantador Tercer Mundo al que quieren renunciar sigue estando ahí, y la tensión es evidente. Como manifestación de esta paradoja pienso en las bicicletas eléctricas y el esfuerzo por controlar la emisión de gases de los vehículos (cosa evidente ya que no vi humo en el escape de absolutamente ninguno) con que esa electricidad es producida por usinas que funcionan con combustión de carbón y que son las que originan gran parte de este smog insoportable. La gente de Asia Central en cambio, si bien tienden a modernizarse, mantiene su vieja identidad, ropas, costumbres, un libro que los une, los condena y los sostiene.  Si bien hay mucha cadena de alimentos occidental, por suerte la comida sigue siendo la de ellos, con insectos y partes de animales que uno ni sueña en su comestibilidad.

</td><td><img src="../itinerario/beijing_ciudad_prohibida/001.jpg" border="0" alt="Beijing." /></td></tr>
<tr>
<td align="center"><img src="../itinerario/beijing_ciudad_prohibida/162.jpg" border="0" alt="Beijing." /></td><td align="center"><img src="../itinerario/beijing_ciudad_prohibida/170.jpg" border="0" alt="Beijing." />&nbsp;&nbsp;<img src="../itinerario/beijing_ciudad_prohibida/180.jpg" border="0" alt="Beijing." />
</td>
</tr>
<tr>
<td><img src="../itinerario/beijing_ciudad_prohibida/068.jpg" border="0" alt="Beijing." /></td>
<td>Partimos a la Ciudad Prohibida, descendemos del Metro y cruzamos un parque sagrado con sus templos y maravillosos árboles milenarios, hasta que llegamos a la Puerta Sur, compramos los tickets y entramos con la marea humana, hay turistas, pero la mayoría  es de gente del país, nueva distinción con otros lugares, también siempre repletos como Efesos, pero la mayoría es de extranjeros.  No sentí la emoción que pudieron darme Tash Rabat o Troya, si en cambio me conmovió la monumentalidad, el cuidado de los detalles, el diseño perfecto de sus terrazas escalonadas en simetrías exactas; el juego de curvas y rectas.  A medida que íbamos avanzando en la Ciudad Prohibida la masa humana se volvía más compacta y en relación directamente proporcional nosotros más incómodos. Poco a poco se nos iba imponiendo la urgencia de la huida.<br /><br />Finalmente en la calle nos pusimos a caminar por una de sus enormes avenidas, en este caso la Jingshan  Kianjie con sentido Este buscando un lugar donde almorzar y la próxima estación de subterráneo. Sin darnos cuenta llegamos frente al Museo Nacional de Arte. Nuestra visita coincidió con 90º aniversario del Partido Comunista y la muestra del Museo estaba dedicada a celebrar este evento con obras de artistas chinos. Imperdible! La maravillosa casualidad que sucede en todo viaje, el evento imprevisto que da nuevas luces. La exposición estaba dividida en tres épocas, 1921 – 1949, 1949-1978 y 1978-2011. Las dos primeras son un show al culto a la personalidad de Mao y  el Gran Salto Adelante, de la Revolución Cultural nada (parece que les cayó alguna ficha), la tercera sección también es un derroche de culto a la personalidad pero del actual presidente, parece que algunas costumbres no se occidentalizan tanto. Fue una experiencia imprevista y extraordinaria acceder a todo el arte propagandístico de 90 años. Y además, no había nadie! Lo que en China quiere decir poca gente y en Occidente un éxito de público.  
</td>
</tr>
<tr>
<td align="center"><img src="../itinerario/beijing_ciudad_prohibida/161.jpg" border="0" alt="Beijing." />&nbsp;&nbsp;<img src="../itinerario/beijing_ciudad_prohibida/080.jpg" border="0" alt="Beijing." />
</td><td align="center"><img src="../itinerario/beijing_ciudad_prohibida/166.jpg" border="0" alt="Beijing." /></td>
</tr>
<tr><td colspan="2">Después fuimos Xidan que es un barrio de Beijing que parece un gran Shopping Mall de varias manzanas de extensión y todo con las mejores marcas. Y todo este consumo, dentro de una teoría comunista?, sostenido por chinos que han crecido económicamente. Impacta mucho más que Rodeo Drive o lugares equivalentes del mundo, París o el que a uno pueda ocurrírsele, por el tamaño geográfico y por la enorme cantidad y diversidad de gente comprando. Ya el día se había prolongado demasiado y no me hacía falta un nuevo no lugar dentro de una ciudad que va en camino de ser un no lugar.
</td></tr>
<tr><td colspan="2"><img src="../itinerario/beijing_ciudad_prohibida/120.jpg" border="0" alt="Beijing." /></td></tr>
</table><table align="center" width="100%"><tr><td align="left"><a href="beijing_primeros_dias.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="beijing_tian.php"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
