<table align="center" cellpadding="10">
<tr>
<td>
Me escribe mi hermana Cristina: "…me gusta que haya casi una insoportable tensión hasta que se produzca el encuentro con el tiempo congelado del desierto como una suerte de súbita descompresión…"<br /><br />
Y esa definición de mi tensión actual describe con perfección mi situación. Resisto este mundo que va a un cambio que me cuesta entender, pero al mismo tiempo mantiene políticas y formas de manipulación de masas que uno desearía inexistentes. La irrelevancia del individuo, la falta de democracia, el uso de cultos antiguos , como el de los ancestros, con fines propagandísticos y de manejo del pueblo, el estado policial eficientísimo en sus controles, el Gran Hermano de verdad, no el de la TV occidental. Una historia de gobiernos autocráticos y luego de dictaduras del siglo XX han conformado un pueblo que acepta mansamente y que no cuestiona demasiado. Han sufrido pobrezas terribles, hambrunas que les han costado millones de muertos, hoy están mejor que lo que nunca soñaron, entonces, de qué quejarse, para qué rebelarse, si incluso las libertades de hoy son las mayores que han conocido. Desde qué perspectiva histórica o cultural puede uno penetrar la realidad de la vida en China hoy? Desde donde acceder a una comprensión equilibrada? Son preguntas que me complican. Los veo perdiendo su lugar, fabricando un no lugar. Y es eso acaso tan importante? Mi tensión actual, en los términos de la descripción de mi hermana llegó con las actividades de hoy a un máximo inesperado. No fue un día sencillo. Veremos si mañana superamos la marca…


</td><td><img src="../itinerario/beijing_tian/067.jpg" border="0" alt="Beijing." /></td></tr>
<tr>
<td><img src="../itinerario/beijing_tian/042.jpg" border="0" alt="Beijing." /></td><td><img src="../itinerario/beijing_tian/047.jpg" border="0" alt="Beijing." />
</td>
</tr>
<tr>
<td><img src="../itinerario/beijing_tian/044.jpg" border="0" alt="Beijing." /></td>
<td>Ya al llegar a China noté que tenía problemas con mis conexiones a Internet. Conocía lo de las "restricciones" a Facebook y redes sociales, luego ví que el acceso a mis lugares también se complicaba. Hubo un momento, hasta que cambié de proveedor en que sólo podía comunicarme por Skype. Ahora estoy un poco mejor, he logrado mandar las notas y las fotos (como podrán ver), pero uno no está acostumbrado a este tipo de "limitaciones".
La presencia policial es menor que la de los uzbekos, pero son mucho más serios y no se andan con chiquitas. En todas las entradas de subterráneo revisan las bolsas, portafolios, mochilas, etc… todo es pasado por máquinas de Rayos X y en caso de duda se procede al chequeo manual.  Todo se filma permanentemente, se tiene la sensación de estar rodeado de cámaras.<br /><br />
El caso es que nos fuimos a la Plaza Tian'anmen a ver la momia de Mao y visitar la histórica plaza. En las entradas de la plaza había cuatro puestos de control con máquinas de rayos, con masas de gente apiñadas en completo desorden, como si fuéramos hacienda vacuna muerta de sed accediendo a una sola aguada, tratando de pasar por estos puntos. Una verdadera tortura. Yo la miraba a Rosario y le preguntaba: "Realmente tenemos que ver la momia de Mao"  y Rosario me contestaba cosas como: "Desde chiquita fui necrofílica". Hacía calor, pero apenas nos metimos en medio de la masa sentí que la temperatura se elevaba espontáneamente como 10º. Así habremos estado como 20 minutos. Cuando quisimos ponernos en la larguísima cola que nos conduciría al Gran Conductor, un policía nos sacó de la cola, siempre (pero esto ya es chino) con modales imperiosos, para que dejáramos nuestras pertenencias en una oficina para esos fines, ya que no se podía pasar con cámaras. 
</td>
</tr>
<tr>
<td>
Luego por 40 Yuan más nos adelantó como tres cuadras en la fila.  Actividades que uno aprende a realizar en cualquier idioma… La demora en llegar al cuerpo de Mao fue de fácilmente una hora. En el camino la policía iba ordenando la fila a los gritos y la gente les daba una relativa atención. Al llegar al Mausoleo (o en este caso deberíamos decir Maosoleo?), que es un típico edificio racionalista, enorme con esculturas alegóricas en sus puertas de multitudes que continuaran con la obra iniciada por el yacente, pasamos por un nuevo chequeo, de documentos y físico, uno por uno. Finalmente subimos las escalinatas, se pasa por una gran sala donde la gente deposita las flores (todas iguales) que venden los guardianes después del último puesto de control y de ahí pasamos al salón mortuorio, donde yacía Mao. Su cara brillaba fuertemente, como si surgiera luz de dentro de ella, en tonos anaranjados. Una escenografía impresionante. Dos pasillos van rodeando el tálamo que está separado de los peregrinos por paños integrales de vidrio.<br /><br />Una vez fuera del edificio Rosario se dedicó a su filmación del lugar parta el documental. Se iba moviendo de un lugar a otro con trípode, filmadora y mochila. Dentro de la multitud nos encontrábamos y perdíamos repetidamente, trataba de guardar el sentido de marcha de su filmación y así íbamos deduciendo donde encontrarnos. Hasta que al final, ya filmados plaza, mausoleo, monumento a los héroes  y demás la encuentro filmando, pero con un policía parado al lado de ella. Ella se movía en alguna dirección, él la seguía, giraba ella, giraban los dos y así como una compañía inseparable, totalmente atento a lo que ella estaba realizando, todo esto además en la más circunspecta posición de firmes. Llegué,. Vi  esto y lo saludé. Ni mu. Lo interrogué con la mirada, algún enarcamiento de cejas, prudentes gestos con las manos, pero el muchacho, nada. Y encima ahora, cada tanto, también me miraba a mí.

</td><td><img src="../itinerario/beijing_tian/046.jpg" border="0" alt="Beijing." /></td></tr>
<tr>
<td><img src="../itinerario/beijing_tian/075.jpg" border="0" alt="Beijing." /></td>
<td>Saco algunas fotos de esta situación rayana en lo ridículo y le digo a Rosario que si terminó mejor nos vayamos de ahí. Cruzamos la avenida por un pasaje subterráneo en dirección a un parque previo a la Ciudad Prohibida. Por supuesto  en el camino había un nuevo puesto de control. Yo como siempre, sólo llevo la cámara, paso sin problema. A Rosario como es habitual le revisan  la mochila, pero esta vez además le piden el pasaporte, inmediatamente se lo retienen y la hacen pararse a un costado. Vuelvo a ver qué pasa y retienen el mío también. Nos paran a un costado y nos dicen que esperemos que ya va a venir un traductor. Todo esto permanentemente contenidos por 3 policías que se mantenían alrededor nuestro. Después de casi una hora llega un policía de Migraciones que hablaba bastante buen inglés, nos cuestiona porqué no  tenemos nuestra documentación original, les habíamos entregado fotocopias porque los originales estaban en el Consulado de Mongolia para su visado. Nos explica que estamos cometiendo una infracción, le pregunta a Rosario si trabaja para algún medio y que por qué ha estado filmando a la policía en la Plaza!?. Para terminar nos dejan ir con una nota de arrepentimiento escrita de puño y letra por Rosario, con varios consejos y el más importante de todos, que trate de no llevar trípode cuando está filmando… Parece que los trípodes son sospechosos!! Tomaron nuestros datos completos, dirección de nuestro hospedaje y nos advirtieron que más valía que no mintiéramos porque iban a corroborar todos nuestros dichos en Internet. Previo a nuestra reganada libertad tuvimos que borrar las escenas que les molestaban. Así iba terminando nuestra jornada de visita a Tian'anmen y los despojos mortales de Mao.
Tiene razón mi hermana, la tensión se hizo levemente insoportable… <br /><br />¿Cuánto falta para el desierto de Gobi?

</td>
</tr>
</table><table align="center" width="100%"><tr><td align="left"><a href="beijing_ciudad_prohibida.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="la_gran_muralla.php"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
