<table align="center" cellpadding="10">
<tr>
<td>
<strong>Domingo 3 de Julio</strong><br /><br />
Finalmente la Gran Muralla. Muralla inútil que se fue construyendo a lo largo de centenares de años, con distintos formatos y diferentes posiciones geográficas, también con distintos materiales. Aunque sí mantuvo un material en forma constante a través del tiempo de su construcción. Así como en Siberia los obreros de la famosa Autopista de los Huesos eran enterrados en ella, lo mismo sucedió con la muralla. Sus trabajadores muertos forman parte de esa inútil barrera hacia el afuera, increíblemente eficaz como límite interior. La muralla no es más que la manifestación física de siglos de xenofobia y aislamiento. No me conmueve pensar en ella, no me conmovió visitarla. Como a todas las murallas, recordemos la Línea Maginot, al agresor, en una actitud paradojalmente china, le bastaba con rodearla, o como en el caso de Troya, en una actitud típicamente occidental, comprar un traidor que abriera las puertas de la misma.<br /><br />Rosario y yo coincidimos en varias cosas y una fundamental es que detestamos los tours y los guías, así que decidimos tomarnos el 919 en Dengshengmen, que va a Badaling, que es donde está la entrada a la muralla. Sólo que el 919 hace dos líneas una que es la que nosotros debíamos tomar y otra que va a cualquier otro lado. Si anticiparon el resultado se equivocaron… Avisados de esta situación tomamos la línea correcta. Pero encontrar la parada y saber cuál es el ómnibus que se debe tomar nos llevo bastante tiempo y charlas incomprensibles (¿?) con chinos que andaban por ahí. 


</td><td><img src="../itinerario/la_gran_muralla/great_wall_01.jpg" border="0" alt="La Gran Muralla." /></td></tr>
<tr>
<td><img src="../itinerario/la_gran_muralla/great_wall_03.jpg" border="0" alt="La Gran Muralla." />
</td>
<td>El viaje a Badaling es de aproximadamente 1 ½ hora para recorrer los 51 kilómetros de distancia. En el colectivo iba una guía que explicaba en chino cosas relativas a la muralla, todas por cierto de enorme importancia, pero que no pude entender. Esta incomprensión lingüística hizo que me detuviera en la articulación de su discurso. Era algo increíble, 30 minutos sin interrupciones, sin puntuaciones, sin titubeos, hasta sin respirar! En esas cosas es donde uno toma contacto con el entrenamiento y seriedad con que encaran su trabajo. Porque esta mujer que es empleada de la línea debe hacer lo mismo varias  veces por día, siempre igual y siempre perfecto. <br /><br />Nuevamente la muralla estaba llena de gente, pero en esta oportunidad muchos más porque era domingo. Sabíamos que era el día menos indicado, pero no teníamos la posibilidad de ir ningún otro. Nunca me imaginé que iba a haber tanta, pero tanta gente… Había más colectivos en la playa de estacionamiento que los que lleva la CGT para llenar la 9 de Julio. Y no estoy exagerando. Tienen  4 terrazas en la montaña que ofician de enormes playas de estacionamiento. Todas llenas. Cuando volvimos tuvimos que hacer una cola de 38 minutos hasta que logramos subir al micro. Lo más lindo de la Muralla es el camino. Asciende unos 700 metros por las laderas de unas montañas cubiertas de árboles, casi diría de un bosque tropical. De paso cruzamos Beijing lo que nos dio la posibilidad de ver más y que el crecimiento no es sólo en las áreas comerciales o turísticas. Todo está en permanente construcción. Será esa la Revolución Permanente de la que hablaba Trotsky??</td>
</tr>

<tr>
<td>
Una nota aparte merece el barrio donde vivimos. Es un viejo barrio que todavía mantiene sus hutongs (pasillos, pasajes, callejuelas, etc…), uno de los lugares más tradicionales y antiguos del viejo Beijing. En el lago Xihai están los pescadores, pescadores que me hacen acordar a mis amigos pescadores de la Argentina. Me sorprendió ver el tamaño de los peces, de unos 50 cts., sino más. Ya me armé una rutina matinal tempranera, paseo por las callecitas, me paro en la ventanilla donde preparan jian bing, que es un enorme panqueque chino, me encargo uno y me lo voy a comer al lago, mientras contemplo a los pescadores o a la estatua de lo que creo un santo taoísta. Es la otra China, sobre la que uno leyó de chico. La que uno quería imaginar en Lao Tse o en los cuentos mágicos. La China de lo irreal, de lo fantástico,  de los milagros,  de los monjes caminantes. Y es que no hay una y referirse sólo a una no es sólo un acto de ingenuidad, sino de incompetencia intelectual y soberbia orientalista. Lo que yo vi fueron sólo aspectos de una ciudad, de Beijing. Eso no es todo China, es sólo lo que me tocó ver y en esta oportunidad.
</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<img src="../itinerario/la_gran_muralla/great_wall_06.jpg" border="0" alt="La Gran Muralla." />&nbsp;&nbsp;&nbsp;&nbsp;<img src="../itinerario/la_gran_muralla/lama_temple_10.jpg" border="0" alt="La Gran Muralla." /></td></tr>
<tr>
<td><img src="../itinerario/la_gran_muralla/tian_anmen_04.jpg" border="0" alt="Beijing." /></td>
<td><img src="../itinerario/la_gran_muralla/ciudad_prohibida_08.jpg" border="0" alt="La Gran Muralla." /></td>
</tr>
<tr>
<td><img src="../itinerario/la_gran_muralla/lama_temple_09.jpg" border="0" alt="Beijing." /></td>
<td>Por la tarde fui al monasterio Lama de Yonghe  Gong. Es el templo de budismo tibetano más importante de Beijing. Fue construido en el S XVII y Chou En Lai lo salvó de la destrucción en la época de la Revolución Cultural. Es un templo con varios santuarios o edificios diferentes donde hay diversos Budas y Bodhisatvas. Frente a todos ellos la gente quema incienso y realiza sus oraciones. Como no está permitido tomar fotos dentro de las salas me tuve que limitar a mirarlos, lo que también es bueno. Asombra la cantidad de Budas distintos, guerreros y feroces, eróticos, meditando, dedicados a condiciones específicas… En fin, para todo lo que uno necesite o quiera rendir culto. Los santuarios eran como 7 distintos y el más imponente es un Maitreya de  sándalo de 17 metros de altura. Impresiona el desarrollo y trabajo de los diferentes edificios, los techos y los trabajos en los cielorrasos. También en este caso estaba lleno de gente, pero por lo menos eran menos ruidosos y el ambiente era tranquilo y agradable. El barrio donde está el templo también mantiene sus hutongs y es un gran centro comercial de objetos relacionados con el budismo. Como una gran santería.<br /><br />Día a día Beijing va cerrando su ciclo. No me alegra, pero si me alivia, nada de lo que pasó me causó extrañeza o me hizo sentir que vivía algo inverosímil. Hoy el incidente con la policía en la Plaza Tian'anmen es sólo una anécdota menor, una nota de color, una interruption para que los amigos se rían de uno en una ronda de whiskies.
</td>
</tr>

<tr>
<td>No estuvimos muy prudentes en un país que es sabido que no practica una democracia abierta. Tampoco me acerqué a este país pensando que iba a estar rodeado de pacíficos e inmóviles brahmanes (es valiosa la comparación que hace Kapuscinski entre la India y la China de los '50s, en esos mismos términos, ya entonces). Es proverbial la laboriosidad y el foco en la acción que ponen y a ningún desprevenido se le cae que son una multitud, no una marea, un tsunami humano y que además se mueven en grandes bloques. No puedo, ni debo quejarme de todo esto porque era toda información que ya tenía. Pero uno es así, se enamora de la chica de mala fama y después se lamenta cuando se enfrenta a lo que ya sabía… La realidad es que en mi caso no hay lamentos. Haber visto de primera mano, en forma directa la transformación económica, e incluso política y cultural es un privilegio que de ninguna forma debo minimizar; sino por lo contrario sentirme como me siento, inmensamente gratificado por haber visto sus monumentos antiguos, sus nuevos edificios, sus partes aún en construcción y haber podido constatar que aún detrás de una uniformidad asombrosa sigue habiendo diversidad, individualidad y originalidad, aunque de manifestación distinta a como nosotros estamos acostumbrados.<br />

</td>
<td><img src="../itinerario/la_gran_muralla/lama_temple_11.jpg" border="0" alt="Beijing." /></td>
</tr>
<tr><td colspan="2">Retiré los pasaportes con las visas, mañana a las 7:47 partimos en el tren K23, el Transmongoliano, a cruzar el Gobi (Гови) y llegar el miércoles al mediodía a Ulaanbataar. Sólo llevamos una semana viajando recién y ya parecen años, tan intenso ha sido todo lo que hemos vivido!
Partimos a Mongolia… Todas dudas, ninguna certeza. Quizás sea esa una definición de la felicidad, cuando todo está por verse y nada se sabe.
<br /><br /><img src="../itinerario/la_gran_muralla/lama_temple_021.jpg" border="0" alt="Beijing." /></td></tr>
</table><table align="center" width="100%"><tr><td align="left"><a href="beijing_tian.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="ulaanbaatar_k23.php"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
