<table align="center" cellpadding="10">
<tr>
<td colspan="2"><strong>19 al 25 de julio</strong><br /><br />
Nos pasó de todo, y es sólo el comienzo… Pudimos retirar la ropa el 19 de julio de Aduana y dejamos preparados los bolsos para salir al día siguiente temprano. La ropa merece una nota aparte, es  increíble la tecnología de REV'IT! Las camperas y los pantalones son comodísimos y con dos capas desmontables, una térmica y la otra es la membrana impermeable;  es destacable la calidad de las terminaciones y de los materiales utilizados, además  de la confección, nunca había probado ropa tan confortable, tanto arriba como fuera  de las motos.  Las botas son comodísimas y bastante frescas para el desierto, cruce un par de vados y como si nada. Lo mismo los guantes que si bien tienen muy buenas protecciones y detalles de "limpiaparabrisas", no son nada aparatosos ni llamativos. No podíamos estar más contentos, la espera bien había valido la pena!<br /><br />
El 20 amaneció lluvioso y con mal pronóstico para el resto del día. Ya habíamos esperado tanto que no valía la pena salir con un día tan espantoso. Nos quedamos y aprovechamos para revisar a fondo el itinerario y terminar de armar algunas cosas más. Finalmente salimos el 21 con destino a Bayan Önjuul, unos meros 130 kilómetros, apenas una distancia como para calentar motores en el mundo normal. Pero este no es un viaje normal, en caminos y condiciones normales. Agarramos la Avenida de la Paz, cruzamos el Puente de la Paz y tomamos la avenida Chinggis Khaan buscando la ruta a Mandalgobi. Paramos en una estación de servicio para llenar tanques, completamos, arranco mi moto, pero la de Rosario se empaca y no arranca más con evidentes problemas de electricidad. No son las nueve todavía. Pido asistencia mecánica que por suerte aparece como a las 12,30 hs. Hacemos un picnic en la estación de servicio y a las 14 salimos. La moto… tenía de todo, un corto en la bocina que le chupaba la carga a la batería, la dínamo que no cargaba y así todo.

</td></tr>
<tr><td><img src="../itinerario/bayan_onjuul/26.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td><td><img src="../itinerario/bayan_onjuul/34.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td></tr>
<tr>
<td>Emprendemos la marcha y a los 30 / 40 kilómetros se nos acaba el asfalto, los cruces que tenía marcados en planchetas de muy buena escala no aparecen, los puntos del GPS tampoco, así que a dirigirnos con una orientación general. Ya no me importa tanto estar bien rumbeado a Bayan Onjüül. Con seguir en la ruta a Mandalgobi me alcanzaba. El día era estupendo pero los caminos y su multiplicidad se vuelven incontrolables. Parecería ser que cada mongol que circula abre su propia ruta, ruta que por supuesto nadie mantiene y que cuando se vuelve intransitable empiezan a circular en otra paralela arriba del campo.   Finalmente aparece un caserío, bastante parecido a un obrador. Como sabía que mi dirección general estaba bien, aunque unos kilómetros abierto al Este, paro para pedir indicaciones. A esa altura del partido ya habíamos sufrido algunas caídas y Rosario venía un poco golpeada. Con la persona que mejor logro hacerme entender me indica que tenemos que salir campo a traviesa, cruzar dos cordones de estas maravillosas montañas mongolas y que 60 kilómetros más allá está Bayan Onjüül. Aparentemente, además, nos vamos a encontrar con un camino más adelante. Son las 18 hs, oscurece a las 21, cómo no voy a hacer 60 kilómetros en dos horas a lo sumo? No?  Seguimos la marcha.</td>
<td><img src="../itinerario/bayan_onjuul/68.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" />
</td>

</tr>

<tr>
<td colspan="2">
Nos encontramos con el famoso "camino", pero las condiciones del mismo se vuelven cada vez más complicadas. Iluso de mí esperaba encontrarme con alguna ruta de ripio un poco más ancha, que me indicara que estábamos en la dirección correcta. Era un simple sendero que ni siquiera llegaba a la calidad de esos caminos que tenemos dentro de los campos y que bordean los alambrados. Trepadas y bajadas pronunciadísimas, aparición inesperada de rocas y profundos colchones de ripio fino y arena, donde las motos se clavaban ya que veníamos muy lentamente. Parte por el cansancio y parte por los espantosos obstáculos de la ruta, Rosario comienza a tener caídas más frecuentemente. Yo ya sé cómo opera eso, cada golpe merma las fuerzas y la confianza en uno mismo. Uno empieza a preguntarse dónde se dará la próxima piña. Finalmente y a 35 kilómetros de nuestro destino decidimos acampar. Nos quedaban una botella grande de agua mineral y unos maníes para comer esa noche. Nos tomamos media botella y reservamos la otra mitad para el día siguiente.</td></tr>
<tr><td colspan="2"><img src="../itinerario/bayan_onjuul/83.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td></tr>

<tr><td>Nos levantamos, desayunamos la media botella de agua restante y seguimos camino. Todo lo que tenía de extraordinario el paisaje coincidía en relación directa con lo desastroso del piso. Después de un par de horas encontramos un ger solitario, Enfilo para ahí, parte por sed y parte para pedir instrucciones. Nos dan un poco del salado té mongol, unos pedazos de queso y nos dicen que Bayan Onjüül está a 30 kilómetros derechito, derechito a una montaña que se ve en el horizonte. Por supuesto no hay camino, pero ya lo vamos a encontrar. Lo encontramos, pero el camino parece un médano. Todo cubierto de arena en la mayor parte de su recorrido, tanto que muchas veces preferimos ir por el campo antes que circular por él. Continuamos con la serie de caídas hasta que en una de las tantas a eso de las 14 hs, vuelvo a auxiliarla a Rosario y sin querer toco con mi pedal la moto de ella y me voy yo también al piso! Paramos las motos, arrancó la de Rosario, luego la mía, pero cuando quiero bajarla del caballete, que está enterrado hasta la mitad no tengo fuerza suficiente. Trato de sacarla andando, como otras veces he hecho y lo único que logro es enterrarla más. Rosario para la de ella, movemos la mía a pulso, ponemos en marcha la de Rosario, la mía no sólo vuelve a enterrarse, sino que ya no arranca más y yo estoy extenuado y casi deshidratado. Me cuesta hasta moverme. Me tiro al piso intentando reponer energías por  unos 15 minutos, pero es inútil. Miro hacia el horizonte, de un lado veo las primeras dunas blancas y del otro tres grupos de gers, dos de dos ger cada uno y el otro mucho más numeroso, por lo menos compuesto por  4 gers.    </td><td><img src="../itinerario/bayan_onjuul/144.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td></tr>



<tr>
<td><img src="../itinerario/bayan_onjuul/351.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td>
<td>Decidimos que Rosario vaya en su moto, que sí logramos hacer funcionar, al grupo mayor de gers y busque auxilio. La veo partir, sigo su marcha hasta que desaparece entre las matas verdes de los pastos del desierto. Miro la hora, son las 14,estimo que en una hora estará de vuelta. Llegan las 15 y nada… Yo me tiraba debajo de algunas matas espinosas buscando algo de sombra, igual que un perro a la hora de a siesta, pero esas tiradas duraban 5 o 7 minutos a lo sumo. Agarraba los binoculares y miraba, pero nada. A las 16 ya empecé a inquietarme pensando que le había pasado algo a Rosario y que a lo mejor estaba caída e inmovilizada bajo la moto. Dudo entre salir caminando campo a traviesa o esperar. A las 17 me pongo en marcha. A los 500 metros aparece un auto blanco con Rosario y unos mongoles adentro. Se había terminado de partir el cuadro de su moto a mitad de camino por lo que se cayó y tuvo que seguir caminando.<br /><br />
 Desenterramos mi moto, la arrancamos y me voy campo a traviesa al grupo de gers. Cuando llego la reviso y veo que también se le ha partido completamente el cuadro, en la parte delantera inferior de la cuna. Evidentemente no podemos continuar así, debemos soldar los cuadros.  <br /><br />
En el campamento se estaba celebrando un casamiento mongol a todo trapo y estaba pleno de familiares y amigos de los contrayentes. Todos, absolutamente todos, absolutamente ebrios. Muchos jugando físicamente fuerte, otros melancólicos, pensativos o francamente expansivos, inmediatamente me doy cuenta que en principio lo mejor es no acampar muy cerca del wedding ger. Como siempre sucede alguna mujer se compadece y nos da de comer. No logramos interesar a ninguno de los muchachos en ir a buscar la moto de Rosario, uno sólo la lleva a buscar sus bolsos, pero de la moto ni hablar. No tenían muchas ganas de distraerse de su cometido fundamental, tomar vodka y molestar al de al lado.



</td>
</tr>
<tr><td colspan="2"><img src="../itinerario/bayan_onjuul/109.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td></tr>
<tr>
<td>Rosario partiría al día siguiente a buscar auxilio a Ulaanbaatar mientras que yo me quedaría acampando y disfrutando de la fiesta de casamiento, que por lo visto dura varios días. Partió temprano en una moto de a tres, con ella fue también Ariuka, nuestra joven amiga, que con su primer curso de inglés nos oficiaba de moderna Malinche.<br /><br />
Así que esa mañana quedé solo en el campamento. Ya había trabado algunas simpatías. Uno de los muchachos que estaban ahí me sacó a dar una vuelta por las cumbres de las montañas, en una chopera china bastante destartalada que manejaba con una destreza y a una velocidad que le daría envidia hasta al mismo Valentino. Juro que fue de las emociones más increíbles de las que me tocó vivir. Trepaba la montaña por arriba de las piedras. Yo no sólo no podía creerlo, sino que evaluaba permanentemente el riesgo de esta aventura loca que corría con este mongol divertidísimo  y que creo con algún nivel de vodka en sangre. Estaba con mi traje REV'IT!, pero sin guantes, ni botas, ni casco! Si nos desbarrancábamos éramos carne de hospital, o algo mucho peor, con toda seguridad. 


</td>
<td><img src="../itinerario/bayan_onjuul/284.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol." /></td>

</tr>
<tr>
<td><img src="../itinerario/bayan_onjuul/200.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol." /></td>
<td>La cocinera más grande (en volumen) de todas en un momento determinado me hace entender que uno de los chicos tiene una muela medio podrida y que está muy dolorido, así que le paso una aspirinas. Más tarde veo que uno de los muchachones que gozaba de un interesante nivel etílico y que no hacía más que mirar torvamente en mi dirección, no se sacaba la mano de la boca del estómago. Como 2 + 2 es cuatro deduzco que con todo lo que chupaba debía tener una gastritis de aquéllas. Me le acerco y le doy un par de antiácidos, con lo que logro un inmediato cambio de actitud. Ya envalentonado, me sentía el médico brujo. Por lo que seguí tirando analgésicos, antiácidos y anti diarreicos a troche y moche para gran felicidad de todos.<br /><br />
También hice algunos pequeños regalos muy valorados. Al que me llevo en la moto le regale mi cortaplumas, a otro una bolsa de precintos y así, con pequeñas cosas que me hicieron la vida sumamente agradable. Ahí fue cuando me di cuenta que no les había hecho un regalo de casamiento a los consortes. Así que partí en busca de Baadai, el novio, munido de mi Mongolian phrasebook  y pude hacerle entender sin mucha dificultad el motivo de mi conversación. A lo que me respondió "Dollars?" en un inglés que no le había oído antes. Inmediatamente convocó  a todo el mundo que aún permanecía ahí  y a su mujer Aagii al wedding ger y se sentaron frente al altar. Fue genuinamente emocionante, les entregué el dinero, brindamos con bastante vodka a una hora totalmente razonable, como las 10 de la mañana y me regalaron para que me lleve un pan bizcocho y una serie de quesos que debí llevarme conmigo. Sentí que a partir de ese momento la mirada de todo el grupo sobre mí ya era muy distinta. Ariuka me explicó que ya era parte de los amigos de los novios.

</td>
</tr>
<tr><td colspan="2"><img src="../itinerario/bayan_onjuul/185.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td></tr>
<tr><td><img src="../itinerario/bayan_onjuul/305.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td><td><img src="../itinerario/bayan_onjuul/322.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol" /></td></tr>
<tr>
<td>En esos días pude vivir muy intensamente el carácter expansivo, amistoso y muy físico de los mongoles. Nuevamente mis problemas me regalaban algo extraordinario. Pude ver los preparativos de los que se marchaban, de los recién llegados y de algunos que se habían ido y retornaban. Vi el manejo del rodeo de ovinos y caprinos y el carneo y cocción de una oveja entera.<br /><br />
El domingo llegó el auxilio desde UB. Cargamos mi moto arriba del camión, el resto de las cosas, carpa, bolsas, etc.… Y salimos al campo a buscar la otra moto. Pero… pero… La moto ya no estaba más. Nos la habían robado! No podía creer tanta mala suerte con las motos.  Alguno de los que se resistió a traernos la moto antes de irse se la subió al camión. Fin del viaje en moto, a mi llegada a UB intentaré vender la mía y alquilar un jeep. Se ve que no era éste un viaje para dos ruedas. Me da una bronca enorme no cumplir con mi objetivo, ni con los compromisos adoptados.  Con el diario de mañana todos seríamos ricos y ahora puedo cuestionar una cantidad de decisiones que pueden no haber sido las mejores, pero finalmente de eso se trata todo viaje, al menos de los míos, vivir lo inesperado e improvisar soluciones.<br /><br />
Cuando volví en el camión desde los gers del valle Sharjain Jonbil, con una moto menos y la otra partida al medio me sentía feliz, sucio (con las uñas como si hubiera excavado en un pozo de petróleo y la ropa amarronada de las arenas de estas estepas) e increíblemente afortunado.


</td>
<td><img src="../itinerario/bayan_onjuul/435.jpg" border="0" alt="Bayan Onjüül - Mi Casamiento Mongol." /></td>
</tr>

<tr>
<td colspan="2">Tuve una íntima satisfacción cuando vi que los muchachos del camión tampoco conocían bien los caminos y terminamos recurriendo a mi GPS.  La realidad es que para hacer los 130  kilómetros que nos separaban de UB tardaron 6 horas, eso puede dar la pauta de la dureza del terreno. 130 kilómetros de maravillosos valles y montañas,  con unos caminos destruidos o ausentes. <br /><br />
Yo pensaba, hasta ese momento, que lo peor que me había tocado vivir para rodar era Asia Central y que nada podía ser comparable a aquella deplorable situación, mi imaginación no había llegado todavía a Mongolia, que por supuesto se vio excedida por la realidad.<br /><br />
El 27 partimos nuevamente al Gobi, pero esta vez en Jeep. No puedo más que disculparme ante la gente amiga  que depositó su confianza en mí, especialmente con Martín. Ahora tenemos un proyecto frustrado en su concepción original, pero mutado en su dinámica como pasa habitualmente.

</td>
</tr>

</table><table align="center" width="100%"><tr><td align="left"><a href="siga_el_baile_ulaanbaatar.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="roller_coaster_mongol.php"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
