<table align="center" cellpadding="20">
<tr>
<td colspan="2">
<strong>15 de agosto</strong><br /><br /><br />
Antes de escribir sobre mi visita a Sainshand necesito decir un par de cosas. Primero que en Shambala sentí la compañía continua de Clarita y Markie, ellos entenderán porqué, también cuando prendí incienso en los ovoos   y monasterios siempre estuvo presente Alejandro, y él también sabe porqué. El segundo tema es que creo que es necesario explicar por qué de todos los lugares del Gobi elegí este para mi visita de despedida  y último día en el countryside mongol, situación que me genera fuertes resonancias emotivas, ya que el 18 estaré tomando el tren a Beijing y el 22 ya arribaré a Buenos Aires en vuelo de Air France después de casi dos meses de internación en Asia, el continente de mi predilección.
</td></tr>
<tr>
<td><img src="../itinerario/sainshand/024.jpg" border="0" alt="Sainshand - Shambala & Sunshine" />
</td>
<td>Por qué Sainshand? O mejor, por qué Khamaryn Khiid y Shambala? No creo a esta altura de mis relatos tenga que contar por qué el Gobi. La explicación a estos interrogantes tiene su origen en el año 1803. Ese año nació, en un hogar miserable, Danzan Ravjaa, Quinta Encarnación del Señor Feroz, Santo del Gran Gobi (Ikh Gobi Dogshin Noyon Hutgat), cuya biografía fascinante leí durante este viaje. Son varias las facetas atractivas de este personaje. Era un monje libertino que vivía rodeado de mujeres y muy dado a excederse con la ingesta de vodka, experto en artes marciales y medicina tántrica, su mayor mérito radica en que es la figura literaria más importante de Mongolia. Escribió cientos de poemas y canciones, algunas de las cuales todavía se oyen, fundó el primer Teatro dramático y escribió una ópera, Saran Khökhöö Namtar (Historia de la Vida del Cuclillo de la Luna), cuya representación completa insume un mes. Es en la zona de Sainshand donde funda su monasterio más importante, si bien ordena la construcción de varios, monta el teatro y bautiza como Shambala la montaña que es centro de energía, también en esas montañas están las cuevas donde se recluían los monjes en ayuno por 108 días (sólo 12 lograron hacerlo y varios murieron en el intento). También es donde está la montaña Khan Bayanzurkh Uul, Montaña Negra, que es la forma que adoptó el Tercer Hutgat Noyon cuando volvió de la ultratumba y vio que no podía retomar su forma humana porque ya habían embalsamado  su cuerpo! Danzan Ravjaa es un personaje lleno de anécdotas, a cual más atractiva y su heterodoxa vida impulsó que mi último día en el Gobi decidiera pasarlo en los lugares que o bien habían sido creados por él, o habían tenido una fuerte relación con su historia. </td>
</tr>

<tr><td colspan="2">Hay un dato de su  vida por demás interesante, además de vaticinar ante sus discípulos en Shambala el momento de su muerte,  lugar que es hoy recordado por un ovoo y una stupa, además de las 108 que delimitan el círculo de energía, también predice que sus bienes personales, que eran muchos y muy valiosos, sufrirán un intento de destrucción completa; por lo que nombra al lama Balchinchoijoo y a sus descendientes cuidadores de sus bienes, y para saber que les cabe ese mérito tendrán como signo distintivo una marca de nacimiento en la espalda, igual a la que tenía el lama mencionado.  Como último dato interesante de este Buda del Gobi habría que mencionar que consideraba a la mujer en iguales condiciones a los hombres y fundamentales para el desarrollo de la religión, lo que le origina serias resistencias y peleas con los sectores más tradicionales del budismo.</td></tr>

<tr>
<td>
Partí el 14 en el tren 285, a las 9 de la mañana y que, penetrando el Gobi  Oriental, llegaría a destino a las 20. Los trenes en Mongolia son de puntualidad inglesa. Mi boleto era "hard sleeper", vale decir, del pueblo. Encantado descubrí que era exactamente lo que esperaba. Son  "camarotes" abiertos de 6 cuchetas que dan a un pasillo común a todo el vagón, sin puertas. El ambiente de tranquilo desorden es bastante agradable. Como no hay vagón comedor, a lo sumo pasa un carrito con sándwiches una o dos veces durante las 11 horas del viaje, cada uno lleva su comida que al poco tiempo comparte con su vecino de "cuarto". Al fondo de los vagones hay unas calderetas con agua hirviendo de las que uno se sirve para hacerse sopas u otras infusiones. Disfruté enormemente del viaje en el que nadie parecía molestarse por el bochinche generalizado. Poco a poco nos fuimos alejando de las montañas y penetrando una parte de este desierto que conocía menos. Cuando llegamos me estaban esperando en la estación el conductor, Battugs, y quien sería mi guía al día siguiente Unursaikhan, una chica pelirroja de 36 años que hablaba un inglés entrecortado, como si fuera rastreando cada palabra que quería usar hasta hallarla. Casi Demóstenes antes de las piedras. Me llevaron al Ger Tourist Camp, comí y me fui a dormir, me esperaba un día siguiente largo.
</td><td><img src="../itinerario/sainshand/003.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td></tr>


<tr>
<td><img src="../itinerario/sainshand/011.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
<td>A eso de las 12 de la noche oigo que empiezan a caer autos, hasta ahí yo era el único huésped del complejo, y reconozco la inconfundible vocinglería gritona de los mongoles. Y no era un grupo chico, no. Eran una banda de gente, un regimiento del ejército de Chinggis Khaan! Me resigné a tener una noche de perros y traté de relajarme y sentirme en un mundo distante. Cerré los ojos, aflojé los músculos y preparándome ya para descansar escucho una guitarra, y atrás de la guitarra un coro de voces y en la melodía que entona el  coro (los mongoles adoran cantar y lo hacen bien y sin inhibiciones) reconozco una de las canciones que había oído en el casamiento en Bayan Onjüül.  Quedé como en suspensión inanimada, totalmente cautivado por estas canciones, como si fueran cantos del desierto. En más de una oportunidad estuve a punto de levantarme e  intentar unirme al grupo. Pero parte por pereza y parte porque también era muy lindo escuchar como si la música viniera de lejos, no me moví de mi lugar. Sentí que el Gobi me daba una última noche encantada, mientras por el agujero central de mi ger veía como se abrían las nubes para darle paso a una luna llena que sentí totalmente compartida. Arrullado por estas canciones me dormí plácidamente. A la mañana siguiente me desperté con el día. Inmóvil en la bolsa de dormir descubrí que la muchachada seguía cantando. No habían parado en toda la noche! 
</td>
</tr>

<tr>
<td>Partimos después del desayuno, y al primer lugar que fuimos fue Shambala. Antes de penetrar en el círculo de energía hay que anunciarse tañendo tres veces una gran campana que cuelga en una especie de pagoda. Tocamos la campana, que en la montaña suena como de otro mundo y nos metimos en Shambala. Y esto no se hace de cualquier forma.  En principio es un lugar rodeado por 108 stupas (número sagrado de los budistas mongoles). El lugar tiene una puerta de oro, por donde se entra y una de plata, por la que se sale. Antes de pasar por la puerta de oro el ingresante debe pararse frente a una pared con unos ojos penetrantes pintados en ella, que  dan una primera carga de energía positiva. El lugar está lleno de símbolos energéticos, lugares de invocación, de sacrificios y de pedido de deseos. También hay boles para alimentos y agua para los pájaros y otros animales. Es como entrar en un lugar abierto donde lo más importante es la paz y espiritualidad que se respira. Es casi imposible permanecer indiferente ante todas las manifestaciones positivas que se perciben. Poco a poco nos fuimos aproximando al ovoo  donde Danzan Ravjaa vaticinó su propia muerte y donde hoy también hay una stupa con un poema y la música de ese poema grabados en la piedra. La poesía es muy linda porque invoca a los 5 sentidos y como estos son despertados por las diferentes manifestaciones de la mujer amada (esencia de sándalo, gusto a miel, etc.…). Estábamos parados ahí cuando Battugs, con perfecta entonación se pone a cantar esta canción de Danzan Ravjaa a viva voz, me conmocionó de inmediato, pero eso no fue nada, porque al segundo verso se le unió Unursaikhan. Sólo nosotros tres en la montaña y esa maravillosa canción que no dejaba de emocionarme. Y creo que lo más tocante de todo fue la actitud con que ellos cantaban. Transmitían convencimiento, fe, respeto y un profundo contacto con sus propias raíces. Cumplimos con todos los rituales de Shambala, quemar un papel con un mal pensamiento escrito en él, decirle nuestro nombre a una piedrita blanca y depositarla en una pila de piedritas blancas y varios más, para luego salir por la puerta de plata. Yo ya estaba en otro mundo. Feliz y emocionado. Pero estas palabras se volverían a repetir durante el día, más de lo que yo pensaba.

</td>
<td><img src="../itinerario/sainshand/059.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
</tr>

<tr><td colspan="2"><img src="../itinerario/sainshand/052.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td></tr>

<tr>

<td colspan="2">De ahí nos fuimos a las cuevas de meditación de los monjes. Pensaba  que serían como celdas monacales. Nada que ver, cuevas minúsculas en piedra viva donde se tapiaban por 108 días. Y por lo menos la segunda mitad de esos días en completo ayuno. Arriba de las cuevas hay un ovoo y también hay una especie de agujero en una roca que dicen que si uno pasa por ahí se le renueva la vida. Así que también pasé por ahí y después me di unas friegas contra  unas rocas sanadoras, que ya están pulidas de tanto que la gente se restriega contra ellas. En camino al monasterio pasamos por un lugar con huesos de dinosaurio y otro con árboles petrificados.

</td>
</tr>
<tr>
<td><img src="../itinerario/sainshand/137.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
<td><img src="../itinerario/sainshand/085.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
</tr>
<tr>
<td colspan="2">Antes de narrar la visita al Khamaryn Khiid es interesante saber que fue lo que sucedió con el monasterio original. En principio fue cerrado en 1931 y sólo quedaron algunos monjes en el templo, entre ellos uno llamado Ongoi, que era cuarta generación de los Takhilch, o cuidadores de los bienes de Danzan Ravjaa, descendiente de Balchinchoijoo. Pero en 1937 y ante la inminencia de la destrucción de los edificios y tesoros contenidos a manos del Partido Comunista Mongol, Tuduv, ya quinta generación de los curadores, entierra todos los bienes del Quinto Noyon Hutgat en el desierto, en 64 lugares diferentes. Tuduv tiene una hija, pero nunca la participa de sus secretos. Esta hija a su vez tuvo diez hijos y el tercero nació con la mancha en la espalda que todos los takhilch comparten. Cuando la hija ve esta marca lo comparte con su padre como un dato curioso ya que la identifica como igual a la de su progenitor. Tuduv le pide a su hija que le entregue ese nieto para educarlo, ya que aduce necesitar a alguien para su vejez. Altangerel, ese es el nombre del nieto, es entregado a Tuduv y éste comparte con él el secreto de donde están enterrados los tesoros y le enseña el arte de la conservación de los mismos. Tuduv muere de muerte natural y Altangerel queda a cargo de los bienes enterrados de Danzan Ravjaa. Ante la caída del comunismo hace un museo y desentierra parte de las cosas. No las más valiosas porque considera que no están dadas las condiciones de seguridad mínimas para hacerlo. Altangerel a su vez tiene un hijo, con también la mencionada marca, a quien está educando como futuro takhilch. Durante el desayuno esa mañana yo le había pedido a Unursaikhan si en la visita de la tarde al museo podríamos verlo a Altangerel. Me interesaba conocerlo porque admiro a la gente que puede preservar bienes de la destrucción de los totalitarismos o de la mera barbarie (por no mencionar a Bush y la destrucción escandalosa de Bagdad).




</td>

</tr>
<tr><td>Del bosque petrificado nos fuimos al Khamaryn Khiid, pasamos primero donde había sabido estar el teatro construido por Danzan Ravjaa, hoy sólo hay una estela de piedra en el lugar donde se erigió el primer teatro mongol. Y nos dirigimos a los templos, que en ese momento estaban cerrados. Al rato aparece el lama con los monjes y comienzan con los cantos de los sutras. Reconozco en el lama a uno de los monjes fotografiados en el libro "Lama  of the Gobi" de Michael Kohn, que es la biografía que ya mencioné antes, veo que el buda del altar no es otro que, como corresponde, la Quinta Encarnación del Buda del Gobi, saco unas fotos y me siento a escucharlos, como vengo haciendo habitualmente en casi todos los templos. En ese momento entra casi corriendo Unursaikhan, para anunciarme que Altangerel está afuera supervisando unas obras. Me voy corriendo con el libro bajo el brazo y me le presento. Unursaikhan oficia de traductora y yo puedo comentarle la admiración que me despierta el trabajo de preservación cultural que él y sus antecesores han realizado.  Hablamos dos minutos más, me dedica el libro en caligrafía mongola, desde ya que no en cirílico!, y nos sacamos un par de fotos. Quizá esta fue para mí una emoción más fuerte que la de Shambala. Una persona cuya vida, la de sus antecesores y tal vez la de sus sucesores esté destinada al cuidado de objetos de cultura es algo que para mí no es un esfuerzo menor. La dedicatoria fue larga y con intención y eso también es un detalle que no quiero pasar por alto.
</td><td align="center"><img src="../itinerario/sainshand/141.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td></tr>

<tr>
<td><img src="../itinerario/sainshand/147.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
<td>Del monasterio hicimos una pasada rápida por los dos ovoos con forma de pechos de mujer (así se llaman) que mando a hacer nuestro conocido Quinta Encarnación, como manifestación de su respeto y admiración por las mujeres. A estos ovoos no se pueden acercar los hombres. Así que la Roca Fálica en Karakorum y los Pechos de Mujer en Sainshand. Hay detalles francamente exquisitos en estos lares.<br /><br />
Almorzamos y luego de un breve descanso encaramos la Montaña Negra (Khan Bayanzurkh Uul). Ahí hay dos templos y dos efigies de Buda. Tiene una escalera que llega hasta la cúspide. En los templos hay una especie de Stupa o de enorme jarrón para pedir tres deseos. Por supuesto que los pedí y arrojé vodka a la tierra y cumplí con todos los rituales. Que como todo lo mongol son de un sincretismo casi escandaloso. Todo va con todo y veneran todo. Lo shamánico, budista o meramente histórico. Todo les va bien. Ahora uno entiende cuando Marco Polo citando a Khublai Khan dice que respeta a los 4 dioses, porque alguno de ellos en su sabiduría debe estar en lo cierto… La estética de lo construido en esta montaña es absolutamente de destacar.

</td>
</tr>

<tr>
<td><img src="../itinerario/sainshand/124.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
<td><img src="../itinerario/sainshand/183.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td>
</tr>

<tr><td>Ya rumbo a la estación sólo me faltaba visitar el Museo que creó Altangerel en la ciudad con los objetos desenterrados, en honor a nuestro personaje del día, sí, Danzan Ravjaa. Llegamos y nos dicen que el museo está cerrado porque hay un corte de energía eléctrica. Estamos por irnos cuando lo vemos caer a Altangerel, me reconoce, nos saludamos, le comento lo apenado que estoy por no poder visitar el museo y el de inmediato nos hace pasar al museo, hace venir a unas chicas a las que mune de sendas linternas y les ordena que me muestren todo. No sabía cómo agradecerle, porque no sé de cuántas encarnaciones más necesitaré para volver a Sainshand. Ya me sentía como un arqueólogo, mirando todo con linternas en la total penumbra, como si estuviera yo desenterrando y descubriendo el contenido de los cofres (cofres que forman parte de lo expuesto en el museo) Pero faltaba la frutilla del postre. Estamos parados frente a lo que vendría  a ser una reproducción de la sala de trabajo del Lama, con una figura de cera representándolo y una pagoda  de oro donde están guardados sus huesos, cuando viene una de las chicas con una botella de vodka y una copa de plata con khadak enlazado a la misma (el khadak es la bufanda de seda que es ofrendada en los ovoos); diciéndonos que nos la mandaba Altangerel, que esa copa era en la que tomaba Danzan Ravjaa y que hagamos unas libaciones rituales, que nos enseña a hacer en ese momento.  Hacemos nuestros brindis rituales y partimos a la estación. Ya eran las nueve menos diez y mi tren salía a las nueve.
</td><td align="center"><img src="../itinerario/sainshand/072.jpg" border="0" alt="Sainshand - Shambala & Sunshine" /></td></tr>

<tr><td colspan="2">Subo al tren y me tocan de compañeros de literas dos hombres con los que había estado pasillo por medio a la ida. Inmediatamente nos reconocemos y empezamos a hablarnos en una mezcla de inglés, ruso, mongol (que no entiendo) y español (que no entienden).  Al rato de salir el tren sacan una botella de vodka, que hacemos circular con disimulo, porque está prohibido el alcohol arriba de los rieles, parece. Al final, la botella también fenece y nos tiramos a dormir. Por la ventanilla veo una enorme luna llena. El pensamiento  que me surge es que quizá la luna llena, como la cultura, no serían tan magnificas si no tuviéramos con quien compartirlas.<br /><br />
<strong>Perdón si esta crónica salió larga, pero  pido amable comprensión; después de todo era mi último día en el Gobi.</strong>
</td></tr>

</table><table align="center" width="100%"><tr><td align="left"><a href="revolucion_permanente.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="#"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
