<table align="center" cellpadding="20">
<tr>
<td colspan="2"><strong>Domingo 16 de julio</strong><br /><br />
Ya termina la semana del Naadam y con un poco de suerte mañana nos juntaremos con la ropa que nos envió Rev'It! desde Holanda.  De ser así entre el martes y el miércoles ya estaremos rumbeando para el sur, pero toda esta serie de demoras que se han ido acumulando, incluso la prolongación de nuestra estadía en Beijing, agregadas a la escasísima confiabilidad de las motos, hicieron que nos viéramos en la necesidad de replantear el itinerario. Así que aproveché estos días de quietud, ya no tenemos mucho más que hacer en UB, y que Rosario estaba muy complicada con el software de edición, por lo que se pasa las horas entre el chat y el estudio y aplicación de distintas soluciones, para revisar y tratar de hacer un itinerario día por día lo más realista posible. Sobre todo sabiendo ahora lo cansador que es el andar de nuestros vehículos.<br /><br />
El tema no implica cambios muy profundos, se mantienen los lugares que más nos interesaban ver y, por supuesto, mantenemos nuestra estadía con la familia nómade, sólo que acortada ahora a un par de semanas. Achiqué sustancialmente las distancias de las etapas diarias, siendo la más larga  de 230 kilómetros. Este ataque de realismo geográfico no sólo se sustenta en la precariedad de las motos, sino también en una geografía muy complicada y no quiero arriesgar andar de noche. Quizá el cambio más importante radica en el sentido de circulación; antes empezábamos por la parte central del país para concluir en el Gobi Austral y ahora iremos en forma directa hacia el sur, como primer objetivo y luego de ahí, si todo está en orden, recorreremos finalmente la parte central en nuestro regreso a Ulaanbaatar. El plan es salir a más tardar el día 20 de julio de UB y estar retornando  entre el 15 y el 16 de agosto, para tomarnos el tren de vuelta a Beijing el día 18 de agosto.<br /><br /> 
Acerca de las comunicaciones, éstas se irán espaciando, probablemente la última que podamos hacer sea el 24 de julio, donde supongo que se interrumpirán totalmente hasta el  9 de agosto. Como siempre, son mayores las dudas que las certezas, y al momento de escribir esto pienso si finalmente algo saldrá  de acuerdo, no ya a lo planeado, pero al menos sí con lo esperado de mínima. Como siempre, todo va a ser distinto… La realidad mantiene su maravillosa capacidad de generar sorpresas.
</td>
</tr>
<tr>
<td><img src="../itinerario/siga_el_baile_ulaanbaatar/029.jpg" border="0" alt="Ulaanbaatar – Música, Maestro!" />
</td>
<td>Decididos a tomar contacto con la tradición musical mongola, sobre todo con el Khuumii que es esa especie de canto gutural típico de acá y con las variaciones de violín de dos cuerdas que se repite en casi toda Asia Central, partimos hacia el teatro que, en la ya típica tendencia local a la síntesis, se llama "Mongolian National Song and Dance Academic Ensemble". El teatro es una construcción de la época soviética, con menos mantenimiento que el necesario, pero no muy venido abajo  y con una cierta gracia. <br /><br />
Pensé que iba a asistir al canto gutural Khuumii, canciones acompañadas por los violines "cabeza de caballo" de dos cuerdas y alguna danzas. De movida ya me pareció medio sospechoso que en el parking hubiera tres ómnibus de turistas. El foyer me hizo acordar al  Margarita Xirgu o a algunos de los teatros de zarzuela de la Avenida de Mayo. La misma onda entre lo vetusto  y lo encantadoramente simpático. Nos ubicaron en fila 6, así que estábamos muy bien respecto al escenario. Abrió con la "Gran Orquesta Nacional" y cuatro cantantes.  La orquesta debía estar formada por más de 40 instrumentistas y tanto mujeres como hombres estaban vestidos con unos deels de seda blanca y puños, cuellos y dobladillos en azul y dorado. La comparación con marineros vestidos de gala fue casi automática, pero inmediatamente me llamé al orden y me dispuse a escuchar seriamente. Los cantantes, también vestidos con deels de fiesta de otros colores, entonaron una canción folclórica. Todo  muy correcto e interesante.  Terminada su canción se retiraron y apareció una cantante que también interpretó  una canción del país y se retiró. Ahí me empecé a dar cuenta que lo que se venía era un muestrario de interpretes con sendas obras cada uno. Totalmente armado y dirigido para los turistas, evitar su aburrimiento y que de paso, en su entusiasmo, compren un CD a la salida. 
 </td>
</tr>
<tr>
<td>Se fue la cantante y quedo la orquesta "naval" sola que arranca con unos acordes que me hizo acordar a Yepes, pero no, no era Yepes, apenas comenzaron con las primeras notas de la melodía reconocí inmediatamente la canción que era… "We are the Champions" del grupo Queen!! La verdad es que me asombró como el folklore mongol sigue manteniendo el sincretismo cultural de la Ruta de la Seda!! Por supuesto que lograron entusiasmar al público que inmediatamente dijo "Qué bueno, está la conozco!!" Pensé en levantarme e irme, pero no tenía nada mejor  que hacer y ya me intrigaba ver como continuaba el show. Finalmente la orquesta termina con una obra irreconocible, pero ya no aseguro su origen, a toda marcha al estilo de Guillermo Tell o Katchatourian.<br /><br />Se fue la orquesta y vino un gordo que sudaba la gota gorda y se cantó un khuumii, acompañándose con un violín cabeza de caballo. La verdad es que estuvo bien. Ayudado por un disimulado micrófono inalámbrico, pero bien. Terminó él y vino una citarista y después un conjunto de cuerdas, estos últimos con claras reminiscencias chinas.<br /><br />
Después nos tocó una pareja de bailarines que intentaba interpretar algo así como un encuentro amoroso casual en las estepas. La música ya era grabada y era cualquier cosa con un aire semioriental, pero que en algunos momentos no tenía el menor empacho en robar algunos ritmos del más preclaro Rock 'n Roll.
</td>
<td><img src="../itinerario/siga_el_baile_ulaanbaatar/004.jpg" border="0" alt="Ulaanbaatar – Música, Maestro!" /></td>
</tr>
<tr>
<td><img src="../itinerario/siga_el_baile_ulaanbaatar/021.jpg" border="0" alt="Ulaanbaatar – Música, Maestro!" /></td>
<td><img src="../itinerario/siga_el_baile_ulaanbaatar/010.jpg" border="0" alt="Ulaanbaatar – Música, Maestro!" /></td>
</tr>
<tr>
<td><img src="../itinerario/siga_el_baile_ulaanbaatar/023.jpg" border="0" alt="Ulaanbaatar – Música, Maestro!" />
</td>
<td>Como las sorpresas continuaban sin límite el locutor nos anuncia que una de las artes escénicas de más fuerte tradición en Mongolia es el contorsionismo y acto seguido, por supuesto, aparece en escena una contorsionista. Yo no lograba salir de mi asombro. Comencé a preguntarme si atrás de eso no vendría un acto de lanzamiento de cuchillos, de magia o la mujer barbuda.<br /><br />
No, por suerte o por desgracia, no sabría decirlo, continuaron con más bailes. Bailes de diferentes tribus todas al mismo tiempo y con la misma música. Baile con muñecas chinas. Baile de máscaras con monjes budistas tocando unas trompas  y platillos infernales. Más bailes grupales y siempre con esta música que iba de lo chino a lo moderno con, quizá, algún lejano toque mongol. Con unos trajes absolutamente ridículos (el traje representativo de no sé qué tribu mongola era un ambo de terciopelo azul, pantalones Oxford, camisa blanca y moño pajarita colorado con lentejuelas!!) Las coreografías eran ridículamente infantiles, supongo que para ocultar la incompetencia del cuerpo de baile, tanto que me hicieron acordar a los actos de baile de cuando mis hijas  iban a ballet, sólo que ellas tenían ocho años en esas performances.  Para dar una idea somera estaban basadas fundamentalmente en violentos trotes y corridas en redondo por el escenario, movimiento de hombros, taconeos, miradas sugerentes y algún gestito manual. En fin, salí del teatro absolutamente divertido con esta muestra de folklore que era exactamente como se lo hubiera podido imaginar un desprevenido y mal informado productor de Hollywood de los comienzos de los musicals.

 </td>
</tr>
<tr><td colspan="2">Sin embargo todo esto me llevo a hacer distintas analogías y razonamientos. Los mongoles, puestos a pueblo sedentario, tienen muy poco propio. Son un pueblo de nómades de las estepas, de grupos humanos reducidos, familias dispersas, que cada tanto se reunían para alguna celebración, o llevar adelante algún ataque a los chinos. Es entonces muy difícil que tengan una arquitectura desarrollada propia, o danzas de cuerpos de bailes, o música de orquesta, o aún una estética muy definida. Pero si fueron los impulsores de la Ruta de la Seda y como tales sí se quedaron con las manifestaciones originales de los pueblos que dominaron o con los que comerciaron. Es entonces lógico, que su arquitectura sea tan "china" y también sus ropas de gala tradicionales,  que mucha de su música me recuerde a los músicos uzbekos y también chinos y que su religión sea el budismo tibetano, desplazando al original shamanismo. Este famoso violín de dos cuerdas está por casi toda el Asia de la Ruta de la Seda.  También pueden verse distintas influencias en los diseños de sus tejidos. En el fondo ellos estuvieron mucho tiempo incorporando y haciendo propio el bagaje cultural de todos los pueblos que dominaron. Y eso se nota y por eso me resulta muy difícil identificar que es dentro de rutinas sedentarias lo "auténticamente" mongol. Si es que la autenticidad existe y esa ya es otra cuestión.</td></tr>
<tr><td colspan="2"><img src="../itinerario/siga_el_baile_ulaanbaatar/068.jpg" border="0" alt="Ulaanbaatar – Música, Maestro!" /></td></tr>
<tr><td colspan="2"><strong> Volví a pasar por el ger del Shaman, pero sigue cerrado, Continuará en éxtasis? Lástima, quería pedirle ayuda espiritual para sacar la ropa de la aduana mañana…</strong></td></tr>
</table><table align="center" width="100%"><tr><td align="left"><a href="un_dia_duro_ulaanbaatar.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="mi_casamiento_mongol.php"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
