<table align="center" cellpadding="20">
<tr>
<td>
<strong>Martes 5 de julio</strong><br /><br /><br />
En el tren me acompañarán el libro de Ryszard Kapuscinski "Viajes con Heródoto" y mi cuaderno rojo donde vuelco los apuntes de viaje.  Viajo con Kapuscinski que a su vez viajó con Heródoto.  El Viaje físico, material, y el viaje del cronista que a su vez viaja en la crónica del otro en una repetición de viajes y crónicas, unas dentro de otras, con el común denominador de la curiosidad y el asombro. No es ésta una comparación, absolutamente improcedente por otra parte con estos gigantes de la crónica, sino un hermanamiento en lo que creo la emoción básica del viajero. Un hermanamiento en la necesaria virginidad de la mirada hacia el otro. Me permito reconfortarme en esa ilusión.
<br /><br /><br /> La estación de Beijing es enorme, bien señalizada, con comodidades y asientos de espera suficientes. Rápidamente encontramos al grupo de extranjeros que ya conocíamos de la cola en el Consulado de Mongolia y nos aprestamos en fila para pasar los controles y acceder a nuestro tren. Una hora antes de la partida abren las puertas de acceso al andén y en perfecto orden vamos buscando el coche que nos corresponde. 
</td><td><img src="../itinerario/ulaanbaatar_k23/164.jpg" border="0" alt="Ulaanbaatar – Tren K23." /></td></tr>
<tr>
<td><img src="../itinerario/ulaanbaatar_k23/019.jpg" border="0" alt="Ulaanbaatar – Tren K23." />
</td>
<td>El tren tiene sólo dos clases: camas duras y camas blandas. Yo me había imaginado que en nuestra clase –camas duras por supuesto- tendríamos unas cuchetas abiertas a los pasillos, como una especie de barracas militares, pero sin colchón, ni ropa blanca, ni ninguna comodidad. Nada que ver. Son camarotes de  4 cuchetas, con un colchón fino y ropa blanca y frazadas completa, y además con compartimientos de tamaño suficiente para guardar todos los bolsos y valijas. Casi como me había imaginado que eran los de "Cama blanda". Estos en cambio son camarotes de sólo dos cuchetas, más lujosos, camas evidentemente  más cómodas, con aire acondicionado, mejor servicio de a bordo y no mucho más. Realmente no valía la pena pagar un 50% más por esas diferencias en un viaje de 30 horas. Además el objetivo es estar con la gente todo el tiempo y no separados de ella.<br /><br />Con nosotros viajaban una joven abuela y quienes suponíamos su hija y nieto, todos de origen mongol. Absolutamente preferible a viajar con alguno de los backpackers europeos que pululaban por el tren. Se ve que nuestras acompañantes tenían experiencia en este viaje porque inmediatamente nos instruyeron en un escasísimo inglés y un profuso mar gestual como debíamos acomodar nuestras cosas y personas dentro de nuestro común hábitat por el próximo día y medio. En seguida se notan las diferencias culturales que registro con curiosidad y simpatía. Las dos mujeres procedieron a cambiarse de ropa, la joven con más discreción se puso un jogging,  la mayor con absoluto desparpajo y desinhibición, una especie de pijama liviano. Todo esto delante de mí y sin ningún tipo de problema. </td>
</tr>

<tr>
<td>
Esta situación de mudar de ropas se repitió dos o tres veces más durante el viaje. En cada oportunidad yo hundía mi cabeza en la lectura de Kapuscinski, o me quedaba absorto mirando por la ventanilla la oscuridad de un túnel, o simplemente me dedicaba a atender infinitamente la limpieza de una uña. Asumí que esta naturalidad era una consecuencia de generaciones de vivir en situaciones de escasa intimidad dentro de un ger.  Conclusión apresurada y sin más elementos que los narrados, pero que, mientras no sea rebatida,  tomaré como teoría válida.<br /><br />El tren con sus túneles va cortando las montañas en un muy suave ascenso, siempre en línea recta, nunca una curva, a una muy buena velocidad. Mientras intentamos capturar algo del paisaje entre túnel y túnel la abuela duerme en la cucheta superior como diciendo mudamente que ella ya ha visto todos los paisajes y que nada vale más que su sueño. En las zonas llanas hay cultivos de maíz, en cada retazo de tierra cultivable, generalmente bordeados por cortinas simples de álamos. También se ven las conocidas usinas de energía con sus enormes chimeneas para el vapor, grandes consumidoras de carbón, principales responsables de la polución en China.<br />Distraído mirando sin atención algunas cosas noto que una pequeña libreta que suele acompañarme está hecha en China; miro mi lapicera, lo mismo; por supuesto, toda la electrónica que llevo, las herramientas, parte de mi ropa y del resto de mi equipo son también chinos. Lo irónico es que todo fue adquirido fuera de este país y ahora todo vuelve  a su lugar de origen. Siempre me sedujeron estas pequeñas situaciones de destinos circulares.
</td><td><img src="../itinerario/ulaanbaatar_k23/126.jpg" border="0" alt="Ulaanbaatar – Tren K23." /></td></tr>
<tr>
<td><img src="../itinerario/ulaanbaatar_k23/104.jpg" border="0" alt="Ulaanbaatar – Tren K23." /></td>
<td><img src="../itinerario/ulaanbaatar_k23/069.jpg" border="0" alt="Ulaanbaatar – Tren K23." /></td>
</tr>
<tr>
<td><img src="../itinerario/ulaanbaatar_k23/099.jpg" border="0" alt="Beijing." /></td>
<td>Dice Kapuscinski: "…si el mundo se rigiese por el sentido común, ¿habría nacido la historia? ¿Existiría?" Intuyo un punto de contacto con Cioran y me sonrío. ¿Tiene alguna relación con lo que veo por la ventanilla? Sin mucha justificación creo reconocer en las manifestaciones anteriores de xenofobia, de crueldad hacia propios y ajenos y en la actual propensión a la desmesura una cierta falta de sentido común. Estaré asistiendo a una nueva escritura de la historia? Todo me induce a pensar que sí. Que todo lo que estoy viendo es parte medular de un profundo cambio histórico. <br /><br />
De repente el camarote es un ger. La abuela mongola está muy concentrada arreglándose las uñas de los pies mientras yo me pierdo en mis cavilaciones escarbándome los dientes y el resto duerme. Imperio de la intimidad indiferente.<br /><br />
Mi ventanilla me sigue mostrando fábricas, usinas y cementeras en forma casi continua. Rutas en construcción, represas. Todo lo que no está en proceso de hacerse parece recién hecho.  Cada vez que pasamos por una estación veo trenes con 60, 80 100? vagones cargados con carbón esperando para entregar su carga de energía. Es casi imposible de evaluar la capacidad instalada existente y la que está en vías de realizarse.  Llegando a Datong quizá la última ciudad de gran importancia se ven hectáreas de edificios de vivienda en torre. Todos vacíos, en proceso, una ciudad de torres, casi rascacielos, todavía desocupados, parte de la planificación. Grandes palomares a la espera de la multitud de sus ocupantes. No tengo dudas, China no tiene vuelta atrás.
</td>
</tr>

<tr>
<td>Después de Datong comienzan a espaciarse los asentamientos, el color de la vegetación va cambiando y los árboles a escasear. El desierto va anunciando  su proximidad. Pasamos 30 kilómetros al Este de una ciudad llamada Shangdu, será la vieja capital de verano de Kublai Khan? La mítica Xanadú? Mi imaginación vuela a esos palacios de mármol que hace poco se han redescubierto y a las cacerías que se organizaban, tan bien narradas por Marco Polo, para regocijo del espíritu cazador del emperador mongol. Pero sé que no, que simplemente un nombre, de los miles similares que hay aquí, me ha traído otro y éste los recuerdos de los relatos de aquel otro viajero. Nuevamente, el viaje dentro del viaje, el relato del relato.<br /><br />
Diez horas después de nuestra partida ya estamos en el desierto. Muy pocos árboles, el pasto ralea. Sólo verdean los bajos y los faldeos de las sierras se amarronan francamente. Aparecen los pastos duros y amarillos y la tierra se va convirtiendo en arena. Estamos en la provincia de Mongolia Interior, territorio, que tal como el Tibet o el Uyghur, es reclamado como propio por sus ocupantes originales, en este caso los mongoles. La ocupación se ve consolidada con el envío de millones de chinos Han, quienes rápidamente superan en número a los habitantes del país dificultando de esa forma cualquier posibilidad de devolución.  Saco los brazos por la ventana, un viento con arenisca en suspensión indica la dureza de la geografía.

</td>
<td><img src="../itinerario/ulaanbaatar_k23/175.jpg" border="0" alt="Beijing." /></td>
</tr>
<tr>
<td><img src="../itinerario/ulaanbaatar_k23/142.jpg" border="0" alt="Beijing." /></td>
<td>Veo mi primera puesta de sol sobre el Gobi. Son las 20 horas.<br /><br />
Llegamos a Erlian ciudad china fronteriza donde hacemos Migraciones y Aduana  y donde cambian los bogies del tren dado que los mongoles adoptaron para sus ferrocarriles la trocha rusa, a efectos de dificultar cualquier  intento de invasión por parte de los chinos. Esto fue a principios del siglo XX. Se llevan el tren a los talleres y los pasajeros nos quedamos en la estación. Pasamos por el escuálido Duty Free, chiquito y de estantes vacíos, que sólo tenía un par de marcas de algunas bebidas y cigarrillos, para luego bajar a un estratégico mini market donde todos nos aprovisionamos para el resto del viaje.  Espontáneamente se fueron armando grupos de pasajeros debajo de los faroles hasta que se desató una tormenta de arena que nos obligó a huir del andén y  buscar refugio dentro de la estación. Pasadas las 23 vuelve el tren y nos ponemos en marcha. A los pocos kilómetros nuevamente aduana y migraciones, pero esta vez del lado mongol. Ya estaba tan dormido que de esta parte me acuerdo poco. Me tomo una sopa instantánea china, tipo Maruchan y me quedo dormido inmediatamente.<br /><br />Me despierto a las 5:00, el sol estaba alto como si fuera media mañana. Estoy todo cubierto de arena, la cara, los ojos, el pelo, las manos, todo. Sin abrir los ojos voy despolvándome como puedo. El tren va mucho más lento y traquetea con un ruido completamente distinto. Evidentemente el estado de los rieles en Mongolia es muy distinto al chino. Me quedo inmóvil un buen rato, tomando contacto con los nuevos movimientos del convoy.  Miro por la ventanilla y sólo asoma la soledad más absoluta. Ya no hay grandes rutas asfaltadas, ni ciudades, ni conglomerados de casas. Sólo unas lomas con ralo pasto amarillo que crece entre la arena.

</td>
</tr>
<tr>
<td><img src="../itinerario/ulaanbaatar_k23/184.jpg" border="0" alt="Ulaanbaatar – Tren K23." /></td>
<td><img src="../itinerario/ulaanbaatar_k23/202.jpg" border="0" alt="Ulaanbaatar – Tren K23." /></td>
</tr>
<tr>
<td colspan="2">Huellas de algún vehículo y nada más. El aire es más fino y frío, la atmósfera diáfana, se adivina lo inhóspito y la dureza, pero también ser percibe la detención del tiempo, un   espacio sin urgencias, el silencio. Me surge la imagen de Chinggis Khan cabalgando con sus hombres por estos lares, hacia el sur en la conquista de los 5 reinos.  
Me pasé todos estos días buscando una palabra que se me escapaba todo el tiempo. Una palabra que describe sintéticamente todo lo vivido. Una palabra cuya existencia conozco, pero que se negaba a aparecer en mi pensamiento. Recurrí a explicaciones y sinónimos insuficientes, pero la palabra se me negaba. Finalmente en la observación del Gobi la palabra apareció sola: contraste. Esa es la mejor definición que puedo dar. Mundos contrastantes hacia afuera y hacia dentro. Contrastantes como quizá nunca pude apreciarlo antes en otros lugares. 
Dejamos el Gobi y nos metemos en las montañas previas a Ulaanbaatar. Ya no más montañas dinamitadas, trepanadas, tuneleadas, ya no más camino recto, ahora el tren dibuja los típicos meandros de los caminos de montaña, ascendiendo y bajando lentamente, traqueteando, con frenadas bruscas. Estos tramos finales me traen el recuerdo del cruce del Caspio en ferry. Qué sensación tan agradable cuando un viaje revive a otro anterior y los recuerdos se van acollarando, trayendo viejas emociones, generando nuevas.




</td>

</tr>
<tr><td>El paisaje se vuelve más verde, aparecen gers, rebaños, gente de a caballo arreando caballos, como si fueran un espejo de otro arreo en algún lugar de nuestras llanuras. Cuando aparecen estas escenas es cuando más creo entender el espíritu que impulsa el nomadismo. Finalmente es Güiraldes quien en una carta rescata a nuestro gaucho como un ser nómade. <br /><br />Rezongando el tren se mete dentro de las nubes bajas y después en la lluvia. La abuela mongola mientras habla con un I Phone 4 de última generación, ya que hemos vuelto a tener la perdida señal de telefonía celular, se cambia de ropa por enésima vez delante de mí. Ya que seguramente quiere estar presentable ante el resto de la familia que debe estar esperándola en Ulaanbaatar.<br /><br />
Son las 14 horas del miércoles, el tren da una última curva hacia la izquierda y por mi ventanilla, al fondo del valle aparece Ulaanbaatar.<br /><br /> Cuando bajamos al andén nos recibe un viento frío cargado de fina lluvia. 
</td><td align="center"><img src="../itinerario/ulaanbaatar_k23/204.jpg" border="0" alt="Beijing." /></td></tr>
</table><table align="center" width="100%"><tr><td align="left"><a href="la_gran_muralla.php"><img src="../images/anterior.jpg" border="0" alt="Nota anterior" /></a></td><td></td><td align="right"><a href="anclados_ulaanbaatar.php"><img src="../images/siguiente.jpg" border="0" alt="Nota siguiente" /></a></td></tr></table>
