<table align="center" cellpadding="10"><tr><td><img src="../images/fundamentos_01.jpg" width="450" /></td><td>El documental que presentamos no puede encuadrarse dentro de lo que en el género se entiende por clásico. No será un trabajo expositivo sin más: estará presente la marca y figura del narrador, encargado de contar con imágenes para producir indirectamente una reflexión sostenida en la inmediatez de la forma cinematográfica. Observar, registrar y trazar nuevos circuitos de pensamiento en torno a viejos temas conocidos en nuestro actual mundo globalizado, determinado por la velocidad con que se producen los cambios. Es la dirección en que se orienta nuestra propuesta documental. Los discursos a explorar son: el nomadismo como opción de vida; la coexistencia de tiempos y atemporalidades; la noción de distancia; la cuestión idiomática; la precariedad del equilibrio actual. Asuntos complejos que, además, deberán ser abordados en el particular contexto del Gobi: un desierto extenso, poblado de vacío, donde los recursos mínimos que demanda una producción audiovisual parecen inaccesibles. 
</td></tr></table>
<table align="center" cellpadding="10"><tr><td>
En concordancia con el nómada, quien no tiene más remedio que reducir al mínimo sus necesidades y satisfacciones materiales, extremando las posibilidades humanas de resistencia ante el azote del frío y del calor, la sed, el hambre y la fatiga, nosotros nos enfrentaremos a la producción del documental con la resistencia que estos mismos materiales proponen. Lo que se cuenta está ligado a las posibilidades (e imposibilidades) de contarlo, lo filmado y el diseño de producción están necesariamente en diálogo. Para articular esta propuesta audiovisual –apoyada en la documentación de lo existente en la cultura mongola- nos valdremos de registros con cámaras de video, registros fotográficos, música, fábulas y cuentos de la zona, costumbres y detalles de la vida cotidiana de las familias nómadas, materiales históricos, textos de poetas, fragmentos y anécdotas de crónicas de viajeros que han estado en Mongolia, materiales geográficos, geológicos, cartográficos y arqueológicos.<div align="right"><p>
                                        <a class="Button" href="modalidad.php">
                                          <span class="btn">
                                            <span class="t">Leer&nbsp;m&aacute;s...</span>
                                            <span class="r"><span></span></span>
                                            <span class="l"></span>
                                          </span>
                                        </a>
                                  </p></div> </td><td><img src="../images/fundamentos_02.jpg" width="450" /></td></tr></table>